.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "YUVCUTTER" "1" "May 2013" "yuvcutter 0.1.0" "USER COMMANDS"
.
.SH "NAME"
\fByuvcutter\fR \- cut frames from raw yuv video files
.
.SH "SYNOPSIS"
\fByuvcutter\fR [OPTION(S)] [\-F FILENAME] [\-H HEIGHT] [\-M YUV_MODE] [\-N NB_FRAMES] [\-W WIDTH]
.
.SH "DESCRIPTION"
\fByuvcutter\fR cuts the first "N" frames from raw YUV video files\. "N" is equal to "1" by default but you can easily change it using \fB\-N\fR option\. YUV supported format are 4:2:0, 4:2:2 and 4:4:4\. Note that as this YUV files are raw files with no information on content, you need to specify the video width and height in order for \fByuvcutter\fR to behave as expected\. By default, it assumes the input video is "1920x1080"\.
.
.SH "OPTIONS"
Common options:
.
.TP
\fB\-h\fR
Show this help and exit\.
.
.TP
\fB\-v\fR
Activate verbose mode\.
.
.TP
\fB\-V\fR
Show program version and exit\.
.
.P
Specific options:
.
.TP
\fB\-F FILENAME\fR
Specify FILENAME as input YUV file\. Default is set to "input\.yuv"\.
.
.TP
\fB\-H HEIGHT\fR
Specify video height\. Default is set to "1080"\.
.
.TP
\fB\-M YUV_MODE\fR
Specify YUV mode used\. Possible values are "420", "422" and "444"\. Default is set to "420"\.
.
.TP
\fB\-N NB_FRAMES\fR
Specify the number of frames to cut\. Default is set to "1"\.
.
.TP
\fB\-W WIDTH\fR
Specify video width\. Default is set to "1920"\.
.
.SH "FILES"
\fByuvcutter\fR expects input files to be non compressed YUV raw video files\. They typically have a \fB\.yuv\fR extension\.
.
.SH "KNOWN LIMITATIONS"
Due to some limitations of the C language (and me being lazy about dealing with it), you will not be able to cut a very large number of frames\. On most computer, this mean that you will not be able to cut more than the number of frames representing the first 512M of the YUV file\. One workaround, if you really want to cut a whole lot of frames, is to run this program several times over the output YUV file\.
.
.SH "BUGS"
Please, report any bug you encounter either directly on the official website: \fIhttp://projects\.gw\-computing\.net/projects/yuvcutter\fR or by sending an email to the author\.
.
.SH "AUTHORS"
Robin Hahling \fIrobin\.hahling@gw\-computing\.net\fR
.
.SH "COPYRIGHT"
Copyright (C) 2013 Robin Hahling
.
.SH "LICENSE"
BSD 3\-clause
.
.SH "SEE ALSO"
ffmpeg(1)
